package utils;

public class UtilConstants {
	public static String json = "{\r\n"
			+ "    \"teams\" : [\r\n"
			+ "        {\r\n"
			+ "            \"team_name\" : \"Pakistan\",\r\n"
			+ "            \"team_score\" : 137,\r\n"
			+ "            \"total_wickets_fallen\" : 8,\r\n"
			+ "            \"overs_played\" : 20.0 \r\n"
			+ "        },\r\n"
			+ "                {\r\n"
			+ "            \"team_name\" : \"England\",\r\n"
			+ "            \"team_score\" : 138,\r\n"
			+ "            \"total_wickets_fallen\" : 5,\r\n"
			+ "            \"overs_played\" : 19.0 \r\n"
			+ "        }\r\n"
			+ "    ],\r\n"
			+ "    \"players\" : [\r\n"
			+ "        {\r\n"
			+ "            \"player_name\" : \"Jos Buttler\",\r\n"
			+ "            \"runs_scored\" : 26,\r\n"
			+ "            \"balls_faced\" : 17,\r\n"
			+ "            \"wickets_taken\" : 0,\r\n"
			+ "            \"overs_bowled\" : 0.0,\r\n"
			+ "            \"runs_given\" : 0,\r\n"
			+ "            \"team_name\" : \"ENG\",\r\n"
			+ "            \"batting_status\" : \"OUT\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"player_name\" : \"Alex Hales\",\r\n"
			+ "            \"runs_scored\" : 1,\r\n"
			+ "            \"balls_faced\" : 2,\r\n"
			+ "            \"wickets_taken\" : 0,\r\n"
			+ "            \"overs_bowled\" : 0.0,\r\n"
			+ "            \"runs_given\" : 0,\r\n"
			+ "            \"team_name\" : \"ENG\",\r\n"
			+ "            \"batting_status\" : \"OUT\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"player_name\" : \"Phil Salt\",\r\n"
			+ "            \"runs_scored\" : 10,\r\n"
			+ "            \"balls_faced\" : 9,\r\n"
			+ "            \"wickets_taken\" : 0,\r\n"
			+ "            \"overs_bowled\" : 0.0,\r\n"
			+ "            \"runs_given\" : 0,\r\n"
			+ "            \"team_name\" : \"ENG\",\r\n"
			+ "            \"batting_status\" : \"OUT\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"player_name\" : \"Ben Stokes\",\r\n"
			+ "            \"runs_scored\" : 52,\r\n"
			+ "            \"balls_faced\" : 49,\r\n"
			+ "            \"wickets_taken\" : 0,\r\n"
			+ "            \"overs_bowled\" : 0.0,\r\n"
			+ "            \"runs_given\" : 0,\r\n"
			+ "            \"team_name\" : \"ENG\",\r\n"
			+ "            \"batting_status\" : \"NOT_OUT\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"player_name\" : \"Harry Brook\",\r\n"
			+ "            \"runs_scored\" : 20,\r\n"
			+ "            \"balls_faced\" : 23,\r\n"
			+ "            \"wickets_taken\" : 0,\r\n"
			+ "            \"overs_bowled\" : 0.0,\r\n"
			+ "            \"runs_given\" : 0,\r\n"
			+ "            \"team_name\" : \"ENG\",\r\n"
			+ "            \"batting_status\" : \"OUT\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"player_name\" : \"Moeen Ali\",\r\n"
			+ "            \"runs_scored\" : 19,\r\n"
			+ "            \"balls_faced\" : 13,\r\n"
			+ "            \"wickets_taken\" : 0,\r\n"
			+ "            \"overs_bowled\" : 0.0,\r\n"
			+ "            \"runs_given\" : 0,\r\n"
			+ "            \"team_name\" : \"ENG\",\r\n"
			+ "            \"batting_status\" : \"OUT\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"player_name\" : \"Liam Livingstone\",\r\n"
			+ "            \"runs_scored\" : 1,\r\n"
			+ "            \"balls_faced\" : 1,\r\n"
			+ "            \"wickets_taken\" : 0,\r\n"
			+ "            \"overs_bowled\" : 0.0,\r\n"
			+ "            \"runs_given\" : 0,\r\n"
			+ "            \"team_name\" : \"ENG\",\r\n"
			+ "            \"batting_status\" : \"NOT_OUT\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"player_name\" : \"Mohammad Rizwan\",\r\n"
			+ "            \"runs_scored\" : 15,\r\n"
			+ "            \"balls_faced\" : 14,\r\n"
			+ "            \"wickets_taken\" : 0,\r\n"
			+ "            \"overs_bowled\" : 0.0,\r\n"
			+ "            \"runs_given\" : 0,\r\n"
			+ "            \"team_name\" : \"PAK\",\r\n"
			+ "            \"batting_status\" : \"OUT\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"player_name\" : \"Babar Azam\",\r\n"
			+ "            \"runs_scored\" : 32,\r\n"
			+ "            \"balls_faced\" : 28,\r\n"
			+ "            \"wickets_taken\" : 0,\r\n"
			+ "            \"overs_bowled\" : 0.0,\r\n"
			+ "            \"runs_given\" : 0,\r\n"
			+ "            \"team_name\" : \"PAK\",\r\n"
			+ "            \"batting_status\" : \"OUT\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"player_name\" : \"Mohammad Haris\",\r\n"
			+ "            \"runs_scored\" : 8,\r\n"
			+ "            \"balls_faced\" : 12,\r\n"
			+ "            \"wickets_taken\" : 0,\r\n"
			+ "            \"overs_bowled\" : 0.0,\r\n"
			+ "            \"runs_given\" : 0,\r\n"
			+ "            \"team_name\" : \"PAK\",\r\n"
			+ "            \"batting_status\" : \"OUT\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"player_name\" : \"Shan Masood\",\r\n"
			+ "            \"runs_scored\" : 38,\r\n"
			+ "            \"balls_faced\" : 28,\r\n"
			+ "            \"wickets_taken\" : 0,\r\n"
			+ "            \"overs_bowled\" : 0.0,\r\n"
			+ "            \"runs_given\" : 0,\r\n"
			+ "            \"team_name\" : \"PAK\",\r\n"
			+ "            \"batting_status\" : \"OUT\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"player_name\" : \"Iftikhar Ahmed\",\r\n"
			+ "            \"runs_scored\" : 0,\r\n"
			+ "            \"balls_faced\" : 6,\r\n"
			+ "            \"wickets_taken\" : 0,\r\n"
			+ "            \"overs_bowled\" : 0.0,\r\n"
			+ "            \"runs_given\" : 0,\r\n"
			+ "            \"team_name\" : \"PAK\",\r\n"
			+ "            \"batting_status\" : \"OUT\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"player_name\" : \"Shadab Khan\",\r\n"
			+ "            \"runs_scored\" : 20,\r\n"
			+ "            \"balls_faced\" : 14,\r\n"
			+ "            \"wickets_taken\" : 0,\r\n"
			+ "            \"overs_bowled\" : 0.0,\r\n"
			+ "            \"runs_given\" : 0,\r\n"
			+ "            \"team_name\" : \"PAK\",\r\n"
			+ "            \"batting_status\" : \"OUT\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"player_name\" : \"Muhammad Nawaz\",\r\n"
			+ "            \"runs_scored\" : 5,\r\n"
			+ "            \"balls_faced\" : 7,\r\n"
			+ "            \"wickets_taken\" : 0,\r\n"
			+ "            \"overs_bowled\" : 0.0,\r\n"
			+ "            \"runs_given\" : 0,\r\n"
			+ "            \"team_name\" : \"PAK\",\r\n"
			+ "            \"batting_status\" : \"OUT\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"player_name\" : \"Mohammad Wasim\",\r\n"
			+ "            \"runs_scored\" : 4,\r\n"
			+ "            \"balls_faced\" : 8,\r\n"
			+ "            \"wickets_taken\" : 0,\r\n"
			+ "            \"overs_bowled\" : 0.0,\r\n"
			+ "            \"runs_given\" : 0,\r\n"
			+ "            \"team_name\" : \"PAK\",\r\n"
			+ "            \"batting_status\" : \"OUT\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"player_name\" : \"Shaheen Afridi\",\r\n"
			+ "            \"runs_scored\" : 5,\r\n"
			+ "            \"balls_faced\" : 3,\r\n"
			+ "            \"wickets_taken\" : 0,\r\n"
			+ "            \"overs_bowled\" : 0.0,\r\n"
			+ "            \"runs_given\" : 0,\r\n"
			+ "            \"team_name\" : \"PAK\",\r\n"
			+ "            \"batting_status\" : \"NOT_OUT\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"player_name\" : \"Haris Rauf\",\r\n"
			+ "            \"runs_scored\" : 1,\r\n"
			+ "            \"balls_faced\" : 1,\r\n"
			+ "            \"wickets_taken\" : 0,\r\n"
			+ "            \"overs_bowled\" : 0.0,\r\n"
			+ "            \"runs_given\" : 0,\r\n"
			+ "            \"team_name\" : \"PAK\",\r\n"
			+ "            \"batting_status\" : \"NOT_OUT\"\r\n"
			+ "        }\r\n"
			+ "    ]\r\n"
			+ "}";
}
